### ISSUE TITLE
ImportError on CASA libraries (.so)

### ISSUE THREAD

**Issue by KarlHeitmann** [kaspervd/casanova#2]
Hello!

I've followed the steps in order to install *casanova*, but I'm getting an **"ImportError: \_\_casac\_\_/_atmosphere.so: failed to map segment from shared object"** whenever I import casa, and the python interpreter gets to the line "_mod = imp.load_module('_atmosphere', fp, pn, desc)" on the file "python_packages/\_\_casac\_\_/atmosphere.py"

I think the problem may be related to PatchELF, so in the installation script, in the loop where you call patchelf on every library file, I've added a "debug command" on line 81:
> echo patchelf --set-rpath '$ORIGIN' $f

In order to see what is happening with the patchelf command, and the results were quite impressive:

```
patchelf --set-rpath $ORIGIN _atmosphere.so
```

As you can see, the environment variable $ORIGIN it seems to be taken as a literal value, however, I've tinkered a little bit, and changed the single quotes on my debug line to this (I've replaced the single quotes by double quotes):

> echo patchelf --set-rpath "$ORIGIN" $f

But the results were quite depressing:

```
patchelf --set-rpath  _atmosphere.so
```

As you can see, the command sent had a empty value on the variable $ORIGIN. Also, I've searched on the install_casanova script the word "ORIGIN", and the only two matches of this search were on line 73 and 81, but on this matches the script is **reading** the value of the variable: this variable has no assignation at all on the whole script. Where does this variable acquire it's value?

Best regards,

Karl

**PS: I'm running OpenSuse Leap 42.2**

**Comment by kaspervd** [comment]
Hi Karl,

Nice to hear that you're using _casanova_! Are you going to implement it in a Jupyter notebook? I have some experience with notebooks myself and I think they're really useful.

I'm sorry to hear that installing _casanova_ did not work out. The $ORIGIN variable refers to the directory containing the application executable ([explanation](https://www.technovelty.org/linux/exploring-origin.html)). Unfortunately I don't work with CASA anymore and this part of the program I largely copied from [Peter Williams](https://newton.cx/~peter/2014/02/casa-in-python-without-casapy/). Hopefully the explanation can help you pinpoint the problem.

I know that the installation of _casanova_ is far from ideal and it took me quite some time to figure everything out. In the ideal case you would like to do something like `pip install casanova` but it would take time to develop this and I don't know how many people use _casanova_. Maybe if there are enough users it's worth creating a group project for this. Then it's also possible to fix the ugly style of importing tasks: `from casat import plotants` and `plotants = plotants.plotants`.

Please let me know if you're able to solve the problem!

Best regards,
Kasper

**Comment by KarlHeitmann** [comment]
Hi Kasper!

I am a member of a computer science team in Chile, and we are working in a project to integrate *casa* in a Jupyter notebook, so the astronomers can download and install the software in order to have all casa's task and tools at hand, and they can also import scripts easily on the notebook. This project is named [caspyter](https://github.com/ChileanVirtualObservatory/caspyter), if you want to take a look.

As a first approach, we took *casanova* as the starting point for the project.

The resources you provided seems to have a lot of useful information, thanks for the feedback, it will sure help us pinpoint the problem.

Cheerio!

Karl


**PS: I've updated my first post, I completely forgot to note that I'm running OpenSuse Leap 42.2**

**Comment by kaspervd** [comment]
Hi Karl,

Sounds like a really cool project! Were you able to fix the problem?

Kasper

**Comment by KarlHeitmann** [comment]
Yes, I could fix it, but I made use of virtualenv, I thought that maybe it wasn't necessary, since you can install casa anywhere you like, and on a place where you have full priviledges.

However, there were some packages you needed to have on you system, like numpy, matplotlob, ipython and jupyter. After installing them on my virtual env, I've had no problem running your scripts.

Thank you again for your response, it's been very important to solve the problem.

Karl
